# Generated by Django 2.1.7 on 2019-06-11 13:20

from django.db import migrations
import markdownx.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='多个标签使用，(英文)隔开', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签'),
        ),
    ]
